# Netlify configuration file for Frontend

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  # Supports React client SPA Router fallbacks
  from = "/*"
  to = "/index.html"
  status = 200
